#!/bin/bash

# Cleans up everything created by deploy-dev-platform-gcp.sh and lb_dns_x509.sh:
# ingress / managed certificate / backendconfig, GKE cluster, Cloud NAT,
# Cloud Router, subnetwork, VPC network and (optionally) the DNS record.
# Author: Matteo Beghelli

GCP_SA_CREDENTIALS_FILE="$1"
PROJECT_ID="$2"
CLUSTER_NAME="$3"
CLUSTER_REGION="$4"

# Optional, set via --vpc-network / --subnet-name.
# When omitted, defaults to the names auto-generated by deploy-dev-platform-gcp.sh
# ("<CLUSTER_NAME>-vpc" / "<CLUSTER_NAME>-subnet").
VPC_NETWORK=""
SUBNET_NAME=""

# Optional, set via --fqdn / --dns-zone to also remove the DNS record created by lb_dns_x509.sh
ABCDESKTOP_FQDN=""
DNS_ZONE="gcp-abcdekstop-demo"

# Set to true via --keep-network to skip deleting the VPC/subnet/router/NAT
KEEP_NETWORK=false

# Set to true via --yes to skip the interactive confirmation prompt
SKIP_CONFIRM=false

# $1 message
# $2 status
display_message() {
    case "${2}" in
        "OK") COLOR="\033[0;32m";;
        "KO") COLOR="\033[0;31m";;
        "ERROR") COLOR="\033[0;31m";;
        "WARN") COLOR="\033[0;33m";;
        "INFO") COLOR="\033[1;34m";;
    esac
    printf "[$COLOR%s\033[0;0m] %s\n" "$2" "$1"
}

# $1 message
display_message_result() {
    exit_code="$?"
    if [ "$exit_code" -eq 0 ];
    then
        display_message "$1" "OK"
    else
        display_message "$1 error $exit_code" "KO"
    fi
}

# $1 command
check_command() {
    if ! command -v "$1" &> /dev/null
    then
        display_message "$1 could not be found" "KO"
        exit 1
    fi
}

check_arguments() {
    if [ "$#" -lt 4 ]; then
        display_message "Missing arguments: expected at least 4 but got $#" "ERROR"
        display_message "Usage: $0 <GCP_SA_CREDENTIALS_FILE> <PROJECT_ID> <CLUSTER_NAME> <CLUSTER_REGION> [OPTION]..." "ERROR"
        exit 1
    fi
}

function help() {
        cat <<-EOF
abcdesktop dev platform cleanup on GCP

Usage: cleanup-dev-platform-gcp.sh <GCP_SA_CREDENTIALS_FILE> <PROJECT_ID> <CLUSTER_NAME> <CLUSTER_REGION> [OPTION]...

Options (exclusives):
 --help                        Display this help and exit

Arguments:
 <GCP_SA_CREDENTIALS_FILE>     Define the path to the service account credentials file
 <PROJECT_ID>                  Define the GCP project id
 <CLUSTER_NAME>                Define the GKE cluster name to delete
 <CLUSTER_REGION>              Define the GKE cluster region

Parameters:
 --vpc-network <name>          VPC network to delete (default: "<CLUSTER_NAME>-vpc")
 --subnet-name <name>          Subnetwork to delete (default: "<CLUSTER_NAME>-subnet")
 --keep-network                Do not delete the VPC network, subnetwork, Cloud Router and Cloud NAT
 --namespace <namespace>       Kubernetes namespace used by abcdesktop (default: abcdesktop)
 --fqdn <domain>               FQDN used for the ingress (also deletes the matching DNS A record)
 --dns-zone <zone>             Cloud DNS zone name (default: gcp-abcdekstop-demo)
 --yes                         Skip the interactive confirmation prompt

Examples:
    cleanup-dev-platform-gcp.sh <GCP_SA_CREDENTIALS_FILE> <PROJECT_ID> <CLUSTER_NAME> <CLUSTER_REGION>
    Delete the cluster and its auto-created VPC/subnet/router/NAT.

    cleanup-dev-platform-gcp.sh <GCP_SA_CREDENTIALS_FILE> <PROJECT_ID> <CLUSTER_NAME> <CLUSTER_REGION> --keep-network
    Delete only the GKE cluster, keep the network resources.

    cleanup-dev-platform-gcp.sh <GCP_SA_CREDENTIALS_FILE> <PROJECT_ID> <CLUSTER_NAME> <CLUSTER_REGION> --fqdn abcdesktop.example.com
    Also delete the DNS A record created for the given FQDN.

Exit status:
 0      if OK,
 1      if any problem

EOF
}

for arg in "$@"; do
    if [ "$arg" = "--help" ]; then
        help
        exit 0
    fi
done

check_arguments "$@"

while [ $# -gt 0 ]
do
    case "$1" in
        --vpc-network) VPC_NETWORK="$2";shift;;
        --subnet-name) SUBNET_NAME="$2";shift;;
        --keep-network) KEEP_NETWORK=true;;
        --fqdn) ABCDESKTOP_FQDN="$2";shift;;
        --dns-zone) DNS_ZONE="$2";shift;;
        --yes) SKIP_CONFIRM=true;;
    esac
    shift
done

[ -z "$VPC_NETWORK" ] && VPC_NETWORK="${CLUSTER_NAME}-vpc"
[ -z "$SUBNET_NAME" ] && SUBNET_NAME="${CLUSTER_NAME}-subnet"
ROUTER_NAME="${VPC_NETWORK}-router"
NAT_NAME="${VPC_NETWORK}-nat"

display_message "abcdesktop dev platform cleanup script" "INFO"
display_message "GCP service account credentials file: $GCP_SA_CREDENTIALS_FILE" "INFO"
display_message "Project ID: $PROJECT_ID" "INFO"
display_message "Cluster name: $CLUSTER_NAME" "INFO"
display_message "Cluster region: $CLUSTER_REGION" "INFO"
if [ "$KEEP_NETWORK" = true ]; then
    display_message "VPC network / subnet / router / NAT: kept (--keep-network)" "INFO"
else
    display_message "VPC network to delete: $VPC_NETWORK" "INFO"
    display_message "Subnet to delete: $SUBNET_NAME" "INFO"
fi
if [ -n "$ABCDESKTOP_FQDN" ]; then
    display_message "DNS record to delete: $ABCDESKTOP_FQDN (zone: $DNS_ZONE)" "INFO"
fi

if [ "$SKIP_CONFIRM" != true ]; then
    printf "This will permanently delete the resources listed above. Type the cluster name (%s) to confirm: " "$CLUSTER_NAME"
    read -r CONFIRMATION
    if [ "$CONFIRMATION" != "$CLUSTER_NAME" ]; then
        display_message "Confirmation did not match, aborting" "ERROR"
        exit 1
    fi
fi

check_command gcloud

# Authenticate with the same service account used by deploy-dev-platform-gcp.sh
# and expose-dev-platform-gcp.sh, so this script has the same IAM permissions
# to delete what those scripts created.
gcloud auth login --cred-file="$GCP_SA_CREDENTIALS_FILE" -q
display_message_result "gcloud auth login --cred-file=$GCP_SA_CREDENTIALS_FILE"

# Get cluster credentials so kubectl targets the right cluster, best effort:
# the cluster may already be gone or unreachable, that's fine for cleanup.
gcloud container clusters get-credentials "$CLUSTER_NAME" --region "$CLUSTER_REGION" --project "$PROJECT_ID" &> /dev/null

# --- DNS cleanup (only if --fqdn was given) ---
if [ -n "$ABCDESKTOP_FQDN" ]; then
    display_message "Deleting DNS A record for $ABCDESKTOP_FQDN" "INFO"
    EXISTING_RRDATA=$(gcloud dns record-sets list --zone="$DNS_ZONE" --project="$PROJECT_ID" \
        --name="${ABCDESKTOP_FQDN}." --type=A --format="value(rrdatas[0])" 2>/dev/null)
    if [ -n "$EXISTING_RRDATA" ]; then
        gcloud dns record-sets delete "${ABCDESKTOP_FQDN}." --type=A --zone="$DNS_ZONE" --project="$PROJECT_ID" --quiet
        display_message_result "gcloud dns record-sets delete ${ABCDESKTOP_FQDN}. --zone=$DNS_ZONE"
    else
        display_message "No DNS A record found for $ABCDESKTOP_FQDN in zone $DNS_ZONE" "WARN"
    fi
fi

# --- Cluster deletion ---
display_message "Deleting GKE cluster $CLUSTER_NAME" "INFO"
gcloud container clusters delete "$CLUSTER_NAME" --region "$CLUSTER_REGION" --project "$PROJECT_ID" --quiet
display_message_result "gcloud container clusters delete $CLUSTER_NAME"

# --- Network cleanup: NAT, router, leftover NEGs/routes, subnet, then VPC (skipped with --keep-network) ---
if [ "$KEEP_NETWORK" = true ]; then
    display_message "Skipping network cleanup (--keep-network)" "INFO"
else
    display_message "Deleting Cloud NAT $NAT_NAME" "INFO"
    gcloud compute routers nats delete "$NAT_NAME" --router="$ROUTER_NAME" --region="$CLUSTER_REGION" --project="$PROJECT_ID" --quiet
    display_message_result "gcloud compute routers nats delete $NAT_NAME"

    display_message "Deleting Cloud Router $ROUTER_NAME" "INFO"
    gcloud compute routers delete "$ROUTER_NAME" --region="$CLUSTER_REGION" --project="$PROJECT_ID" --quiet
    display_message_result "gcloud compute routers delete $ROUTER_NAME"

    # GKE's ingress controller creates zonal Network Endpoint Groups (NEGs) for
    # container-native load balancing (e.g. the "kube-system-default-http-backend"
    # NEG). Their cleanup after cluster deletion is asynchronous and can still be
    # in progress, which blocks the network deletion below with a "resource is
    # already being used" error. Proactively delete any leftover NEG on this
    # network first.
    display_message "Cleaning up leftover Network Endpoint Groups on $VPC_NETWORK" "INFO"
    while IFS=$'\t' read -r NEG_NAME NEG_ZONE; do
        [ -z "$NEG_NAME" ] && continue
        display_message "Deleting NEG $NEG_NAME (zone $NEG_ZONE)" "INFO"
        gcloud compute network-endpoint-groups delete "$NEG_NAME" --zone="$NEG_ZONE" --project="$PROJECT_ID" --quiet
        display_message_result "gcloud compute network-endpoint-groups delete $NEG_NAME --zone=$NEG_ZONE"
    done < <(gcloud compute network-endpoint-groups list --project="$PROJECT_ID" \
        --filter="network:$VPC_NETWORK" --format="value(name,zone.basename())" 2>/dev/null)

    # A VPC network cannot be deleted while custom/default routes still point to
    # it (e.g. the auto-created "default-route-..." to the internet gateway).
    # Subnet routes (routeType SUBNETWORK) and peering routes are managed
    # automatically, so only delete STATIC routes here.
    display_message "Cleaning up leftover routes on $VPC_NETWORK" "INFO"
    while IFS=$'\t' read -r ROUTE_NAME ROUTE_TYPE; do
        [ -z "$ROUTE_NAME" ] && continue
        [ "$ROUTE_TYPE" != "STATIC" ] && continue
        display_message "Deleting route $ROUTE_NAME" "INFO"
        gcloud compute routes delete "$ROUTE_NAME" --project="$PROJECT_ID" --quiet
        display_message_result "gcloud compute routes delete $ROUTE_NAME"
    done < <(gcloud compute routes list --project="$PROJECT_ID" \
        --filter="network:$VPC_NETWORK" --format="value(name,routeType)" 2>/dev/null)

    display_message "Deleting subnetwork $SUBNET_NAME" "INFO"
    gcloud compute networks subnets delete "$SUBNET_NAME" --region="$CLUSTER_REGION" --project="$PROJECT_ID" --quiet
    display_message_result "gcloud compute networks subnets delete $SUBNET_NAME"

    # Network deletion can still fail right after the cleanup above if some
    # dependent resource (NEG, route, firewall rule...) hasn't finished being
    # released on the GCP side yet, so retry a few times with a short delay.
    display_message "Deleting VPC network $VPC_NETWORK" "INFO"
    NETWORK_DELETE_ATTEMPTS=5
    for ((i = 1; i <= NETWORK_DELETE_ATTEMPTS; i++)); do
        if gcloud compute networks delete "$VPC_NETWORK" --project="$PROJECT_ID" --quiet; then
            display_message "gcloud compute networks delete $VPC_NETWORK" "OK"
            break
        elif [ "$i" -eq "$NETWORK_DELETE_ATTEMPTS" ]; then
            display_message "gcloud compute networks delete $VPC_NETWORK error (still in use after $NETWORK_DELETE_ATTEMPTS attempts)" "KO"
        else
            display_message "VPC network still in use, retrying in 20s (attempt $i/$NETWORK_DELETE_ATTEMPTS)..." "WARN"
            sleep 20
        fi
    done
fi

display_message "Cleanup finished for cluster $CLUSTER_NAME" "INFO"